### ISSUE TITLE
Diagrams not rendering in vector solutions

### ISSUE THREAD

**Issue by gvwilson** [jrnold/r4ds-exercise-solutions#109]
In <https://jrnold.github.io/r4ds-exercise-solutions/vectors.html>, Exercise 20.5.4.1, Firefox displays this:
![screen shot 2018-09-18 at 11 24 16 am](https://user-images.githubusercontent.com/911566/45698202-7bd4bb00-bb35-11e8-8aa1-550d52a637be.png)

**Comment by jrnold** [comment]
Reopening because this is still not fixed. It worked locally, so it's probably something with the javascript library not being deployed or given the right permissions.
