### ISSUE TITLE
Badly-formatted footnote (maybe) in vector chapter

### ISSUE THREAD

**Issue by gvwilson** [jrnold/r4ds-exercise-solutions#110]
The footer of <https://jrnold.github.io/r4ds-exercise-solutions/vectors.html> displays this in Firefox:
![screen shot 2018-09-18 at 11 26 43 am](https://user-images.githubusercontent.com/911566/45698365-cfdf9f80-bb35-11e8-81db-469445f7c9c6.png)

Is this an unclosed bracket for a footnote?

**Comment by jrnold** [comment]
Yes. Thanks!
