### ISSUE TITLE
Use three digits to number exersie

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#115]
For example, in [chapter 7](https://jrnold.github.io/r4ds-exercise-solutions/exploratory-data-analysis.html)

The first exercise of section 3 is `Exercise 7.3.4.1`, whereas the first exercise of section 4 is `Exercise 7.4.1.1`. I think this is quite confused.

The first two digits specify chapter & section, the last digit specify which exercise of the section. I think that is enough to uniquely locate the exercise. 

The third digits depends on the relative position of exercise in the section of original book, 7.3 contains three second-level header before the exercise thus the third digit is `4`, while 7.4 contains no second-level header before the exercise thus the third digit is `1`.

**Comment by dongzhuoer** [comment]
A special case is that certain section may contains more than one exercise block, then we need four digits.

**Comment by jrnold** [comment]
I made that change because I think it's more explicit and clear. The exercise is in Chapter 7, Section 3, Subsection 4 (which happens to be the exercise section), problem 1. If many more people find it confusing, I'd change it. It's not the only way to organize it, but it is correct, and I'm happy with it, so I'm not going to change it.

**Comment by jrnold** [comment]
with respect to the three digits: no problem. 

with respect to the subsection issue: yeah, it's a pain. I wish I had a better solution. I initially tried to avoid hardcoding any exercise numbers, but there were even more issues keeping it in sync with the original. And it was hard to link to the exercises or look up which exercise people were referring to in the source. I figure, it if gets out of sync, someone will open an issue about it, then I'll fix it. But until a new edition of the book comes out, I doubt the organization will change too much.

**Comment by jrnold** [comment]
You're
