### ISSUE TITLE
Improve answer for Exercise 13.2.3

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#124]
The question asks, what _additional_ relation would it define with `flights`

Suppose the `origin` column of `weather` gets a new name, `airports`, then additional relation is that `airports` variable in `weather` matches with `dest` variable in `flights`.

**Comment by jrnold** [comment]
I'm not sure that I follow. I expanded the answer to make it more clear (I hope), but the current answer is exactly what you wrote. Right now it only makes sense to merge weather with the origin airport in the `flights` table. With info about all airports it would also make sense to merge it with the destination airport.

**Comment by dongzhuoer** [comment]
I assumed that the _additional_ relation means new relation between columns, i.e., not to include the _existing_ relation, so we don't need to address the `year`, `month`, `day`, `hour` columns.

**Comment by jrnold** [comment]
Relation means the relationship between the tables, which would be defined as foreign keys in a database.  The relationship defined by multiple variables, and in this case it is `flights` (`weather` (`year`, `month`, `day`, `hour`, `origin`) to `weather` (`year`, `month`, `day`, `hour`, `origin`). 

From https://r4ds.had.co.nz/relational-data.html#keys:

> A primary key and the corresponding foreign key in another table form a relation.

However, in this case, the keys are multi-column.

Does that make sense? I'm going to take another stab at improving the wording. Do you have any ideas on how to better convey this?

**Comment by dongzhuoer** [comment]
I think we both understand what happens. But it seems hard to articulate a proper answer.

Maybe the question is not good enough. Ideally, the case should be that a newly added column introduce new relation. But in this case new rows are added in existing columns.

Hope someone else can propose an awesome answer.

**Comment by dongzhuoer** [comment]
Hope someone else can propose an awesome answer!

**Comment by jrnold** [comment]
I am 100 percent  certain that current answer is correct. The question is
straightforward but requires a knowledge of relational databases that is
kind of skimmed over in the back text. This database definition of
relation. What is described would be implemented in SQL by adding another
foreign key constaint. This is not about adding new columns.

**Comment by dongzhuoer** [comment]
Great!

**Comment by jrnold** [comment]
I realized what the answer was missing. The reason the weather table needed extra rows to define a relationship with the destination airport in flights is that a foreign key should be a primary key in a different table. All values of the foreign key must appear in the primary key it is referencing. So until all combinations of destination airport, year, month, day that appear in the flights table appear in the weather table, we cannot define a foreign key relation between those tables.

**Comment by jrnold** [comment]
Thanks for pushing me on this ! :-)

**Comment by persep** [comment]
> 
> 
> I realized what the answer was missing. The reason the weather table needed extra rows to define a relationship with the destination airport in flights is that a foreign key should be a primary key in a different table. All values of the foreign key must appear in the primary key it is referencing. So until all combinations of destination airport, year, month, day that appear in the flights table appear in the weather table, we cannot define a foreign key relation between those tables.

I think there is a better way of rephrasing it. The question is:  So why was this not a relationship prior to adding additional rows to the weather table?
I'd say it's because it would mean that there were flights taking off from one of the NYC airports and landing on the same or different airport in the same city, NYC which doesn't make any sense,ie: flights NYC-NYC, That's why there wasn't a relationship from weather-origin to flights-destination before all the weather stations where added
