### ISSUE TITLE
Exercise 5.4.1.1 solution with column indexes

### ISSUE THREAD

**Issue by JamesCuster** [jrnold/r4ds-exercise-solutions#125]
Hey, in one of the solutions to this questions you select the columns using their indexes. The indices that you use are incorrect. 

What you have is select(flights, 4, 5, 6, 9) which selects dep_time, sched_dep_time, dep_delay, and arr_delay. The indices that should be used are select(flights, 4, 6, 7, 9)

**Comment by jrnold** [comment]
Thanks. I would claim that it was purposely there as an example of why not to use index numbers for columns, but I'm not that clever.

**Comment by JamesCuster** [comment]
Hahaha! Could leave it in for illustration purposes. Question, do you mind/want me to continue to point out things like this and typos I find as I work through the book? Cause I found another typo, but I don't want to become annoying with this small things.

**Comment by jrnold** [comment]
Please do! After the moment of annoyance at seeing another issue passes, I do appreciate it. I mostly wrote this in one go, and I know there are still many typos. I should be apologizing that there are still so many.

**Comment by JamesCuster** [comment]
Ok I will, and no worries. It has been a great resource for checking my work or helping figure things out as I go along so I appreciate you putting it together.
