### ISSUE TITLE
Exercise 13.5.3: add extra explanation for why `model` is not suitable key for `fueleconomy::common`

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#134]
``` r
library(magrittr)
library(tidyverse)
```

I assume `model` can be the prime key.

``` r
fueleconomy::common %>% count(model) %>% filter(nn > 1)
```

    ## # A tibble: 0 x 3
    ## # Groups:   make [0]
    ## # ... with 3 variables: make <chr>, model <chr>, nn <int>

But we can’t use `model` to join the two tables.

``` r
common_vehicle1 <- fueleconomy::vehicles %>% 
    semi_join(fueleconomy::common, by = c("model")) %T>% print
```

    ## # A tibble: 14,631 x 12
    ##       id make  model  year class trans drive   cyl displ fuel    hwy   cty
    ##    <int> <chr> <chr> <int> <chr> <chr> <chr> <int> <dbl> <chr> <int> <int>
    ##  1  1833 Acura Inte…  1986 Subc… Auto… Fron…     4   1.6 Regu…    28    22
    ##  2  1834 Acura Inte…  1986 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  3  3037 Acura Inte…  1987 Subc… Auto… Fron…     4   1.6 Regu…    28    22
    ##  4  3038 Acura Inte…  1987 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  5  4183 Acura Inte…  1988 Subc… Auto… Fron…     4   1.6 Regu…    27    22
    ##  6  4184 Acura Inte…  1988 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  7  5303 Acura Inte…  1989 Subc… Auto… Fron…     4   1.6 Regu…    27    22
    ##  8  5304 Acura Inte…  1989 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  9  6442 Acura Inte…  1990 Subc… Auto… Fron…     4   1.8 Regu…    24    20
    ## 10  6443 Acura Inte…  1990 Subc… Manu… Fron…     4   1.8 Regu…    26    21
    ## # ... with 14,621 more rows

``` r
common_vehicle2 <- fueleconomy::vehicles %>% 
    semi_join(fueleconomy::common, by = c("make", "model")) %T>% print
```

    ## # A tibble: 14,531 x 12
    ##       id make  model  year class trans drive   cyl displ fuel    hwy   cty
    ##    <int> <chr> <chr> <int> <chr> <chr> <chr> <int> <dbl> <chr> <int> <int>
    ##  1  1833 Acura Inte…  1986 Subc… Auto… Fron…     4   1.6 Regu…    28    22
    ##  2  1834 Acura Inte…  1986 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  3  3037 Acura Inte…  1987 Subc… Auto… Fron…     4   1.6 Regu…    28    22
    ##  4  3038 Acura Inte…  1987 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  5  4183 Acura Inte…  1988 Subc… Auto… Fron…     4   1.6 Regu…    27    22
    ##  6  4184 Acura Inte…  1988 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  7  5303 Acura Inte…  1989 Subc… Auto… Fron…     4   1.6 Regu…    27    22
    ##  8  5304 Acura Inte…  1989 Subc… Manu… Fron…     4   1.6 Regu…    28    23
    ##  9  6442 Acura Inte…  1990 Subc… Auto… Fron…     4   1.8 Regu…    24    20
    ## 10  6443 Acura Inte…  1990 Subc… Manu… Fron…     4   1.8 Regu…    26    21
    ## # ... with 14,521 more rows

Why is the difference?

``` r
setdiff(common_vehicle1, common_vehicle2) %>% select(make, model) %>% 
    left_join(fueleconomy::common, by = c("model"))
```

    ## # A tibble: 100 x 5
    ##    make.x   model      make.y       n years
    ##    <chr>    <chr>      <chr>    <int> <int>
    ##  1 Chrysler Limousine  Cadillac    15    15
    ##  2 Dodge    Colt Vista Plymouth    40    10
    ##  3 Dodge    Colt Vista Plymouth    40    10
    ##  4 Dodge    Colt Vista Plymouth    40    10
    ##  5 Dodge    Colt Vista Plymouth    40    10
    ##  6 Dodge    Colt Vista Plymouth    40    10
    ##  7 Dodge    Colt Vista Plymouth    40    10
    ##  8 Dodge    Colt Vista Plymouth    40    10
    ##  9 Dodge    Colt Vista Plymouth    40    10
    ## 10 Dodge    Colt Vista Plymouth    40    10
    ## # ... with 90 more rows

**Comment by jrnold** [comment]
Fixed in 875e566b155a943

**Comment by jrnold** [comment]
Thanks!

**Comment by dongzhuoer** [comment]
![image](https://user-images.githubusercontent.com/15871952/48891461-62722700-ee76-11e8-8add-461ba913b6b9.png)

Maybe you wan to say

> It is possible for two car brands (`make`) to produce a car model with the same name (`model`).
