### ISSUE TITLE
Exercise 14.5.2, make code more concise and **tibble** way

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#140]
original

```r
str_extract_all(sentences, boundary("word")) %>%
  unlist() %>%
  str_to_lower() %>%
  tibble() %>%
  set_names("word") %>%
  group_by(word) %>%
  count(sort = TRUE) %>%
  head(5)
#> # A tibble: 5 x 2
#> # Groups:   word [5]
#>   word      n
#>   <chr> <int>
#> 1 the     751
#> 2 a       202
#> 3 of      132
#> 4 to      123
#> 5 and     118
```

**Comment by dongzhuoer** [comment]
I propose

```r
str_extract_all(sentences, boundary("word")) %>% 
    unlist %>% 
    str_to_lower() %>% 
    tibble(word = .) %>% 
    count(word, sort = T) %>% 
    slice(1:5)
#> # A tibble: 5 x 2
#> # Groups:   word [5]
#>   word      n
#>   <chr> <int>
#> 1 the     751
#> 2 a       202
#> 3 of      132
#> 4 to      123
#> 5 and     118
```

**Comment by jrnold** [comment]
Style comment: `TRUE` and `FALSE` should always be used instead of `T` and `F`. `TRUE` and `FALSE` are constants in the language. `T` and `F` are just variables that happen to be initialized as 
```r
T <- TRUE
F <- FALSE
```
That means this is valid.
```
T <- FALSE
F <- TRUE 
```

**Comment by jrnold** [comment]
```r
str_extract_all(sentences, boundary("word")) %>%
  unlist() %>%
  str_to_lower() %>%
  tibble() %>%
  set_names("word") %>%
  count(word, sort = TRUE) %>%
  head(5)
```

- removing `group_by` makes sense
- does r4ds use the `.` pronoun with `%>%` ? It's more concise but could be more obscure.
- `head()` and `slice()` both work. Which one seems to be more in the style of r4ds?

**Comment by dongzhuoer** [comment]
well, it seems that R4DS rarely use `.` with `%>%`, and often use `head()`

How about this?

```r
word_in_sentences <- sentences %>% 
    str_extract_all(boundary("word")) %>% 
    unlist %>% 
    str_to_lower()  

tibble(word = word_in_sentences) %>% 
    count(word, sort = TRUE) %>% 
    head(5)
```

**Comment by jrnold** [comment]
Definitely better. How about this? 

```r
tibble(word = unlist(str_extract_all(sentences, boundary("word"))) %>% 
    mutate(word = str_to_lower(word))
    count(word, sort = TRUE) %>% 
    head(5)
```

**Comment by dongzhuoer** [comment]
I think `)))` isn't a good idea.

I admit that it's tempting to write all the code in a single statement. But the original purpose of pipe is _to improve readability_.

When we can give the temporary variable a meaningful name (maybe a little long), we should not be afraid to write two (or even more) statement.

**Comment by dongzhuoer** [comment]
And the code should be

```r
tibble(word = unlist(str_extract_all(sentences, boundary("word")))) %>% 
    mutate(word = str_to_lower(word)) %>% 
    count(word, sort = TRUE) %>% 
    head(5)
```

Aha, you already miss a `)`

**Comment by dongzhuoer** [comment]
Maybe 

```r
tibble(word = sentences %>% str_extract_all(boundary("word")) %>% unlist) %>%
    mutate(word = str_to_lower(word)) %>%
    count(word, sort = TRUE) %>% 
    head(5)
```

**Comment by jrnold** [comment]
I think using `%>%` within the parentheses is overusing the pipe. In this case I think that the nesting functions is more readable than piping.

**Comment by jrnold** [comment]
I've already gone through the stage of including trying to pipe everything. And now I've moved back a little. `sentences %>% str_extract_all(boundary("word"))` is less readable than `str_extract_all(sentences, boundary("word"))`. And a single additional function isn't worth a pipe. In any case, at this point, we are at diminishing returns to discussion over code quality.
