### ISSUE TITLE
update exercise number for "14.4 Tools"

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#144]
I have advice Hadley to correct 4th level heading.

![image](https://user-images.githubusercontent.com/15871952/48383057-1fe67700-e71f-11e8-9ae1-17e04479fd0e.png)

**Comment by jrnold** [comment]
What needs to be changed?

**Comment by dongzhuoer** [comment]
![image](https://user-images.githubusercontent.com/15871952/48965127-557a4280-eff2-11e8-980a-8190740c6bc5.png)
Your book doesn't match the original book.
