### ISSUE TITLE
Exercise 28.2.2: remove extra plot

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#149]
I think this one is great and enough
![image](https://user-images.githubusercontent.com/15871952/48552074-618b4380-e912-11e8-9af0-16afaaf03adb.png)

Why do you add the following one?
![image](https://user-images.githubusercontent.com/15871952/48552083-6cde6f00-e912-11e8-862e-72c95602958d.png)

**Comment by jrnold** [comment]
No idea :-) I'll have to reread the problem and see what I was thinking and whether it still makes sense.
