### ISSUE TITLE
Exercise 5.5.2.1: fix for first example in solution

### ISSUE THREAD

**Issue by mvhone** [jrnold/r4ds-exercise-solutions#152]
---
Error in the example at the start of this solution, answer should be 904 minutes after midnight:

![capture](https://user-images.githubusercontent.com/20008439/48640789-ad3afd00-e9a5-11e8-897c-541d47eccc0b.PNG)

Change to:

```r
15 * 60 + 4
#> [1] 904
```

**Comment by jrnold** [comment]
Thanks!
