### ISSUE TITLE
Exercise 16.4.5 miss a `)`

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#156]
![image](https://user-images.githubusercontent.com/15871952/48661020-7e588000-eaa6-11e8-9c73-b2f90d8868d3.png)

In the question, there should be a `)` before `/`.

Maybe that's the answer for the question?

**Comment by jrnold** [comment]
I don't think so; it wouldn't make sense to ask a question where the answer is just an obvious syntax error in a section on dates. That's just a typo in the original question.

The answer should be that an interval is being devided by a period, as discussed in https://r4ds.had.co.nz/dates-and-times.html#intervals. So the answer is to use `%/%`. However, I'm still figuring out why the example here does not seem to raise a warning message, and seems to work fine.
