### ISSUE TITLE
Discussion on Exercise 24.3.7

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#168]
```r
flights %>%
  mutate(date = make_date(year, month, day),
         wday = wday(date, label = TRUE)) %>%
  group_by(wday, hour) %>%
  summarise(dist_mean =  mean(distance),
            dist_median = median(distance),
            n = n()) %>%
    group_by(wday) %>%
    mutate(freq = n/sum(n)) %>%
  ggplot(aes(y = dist_mean, x = hour)) +
  geom_point(aes(color = freq, size = 3)) +
  geom_line(aes()) + 
    coord_cartesian(ylim=c(780, 1300)) + facet_wrap(~wday) + viridis::scale_color_viridis()
```

![image](https://user-images.githubusercontent.com/15871952/48908157-7d5b9000-eea4-11e8-9ffc-d62d36ce92de.png)

**Comment by jrnold** [comment]
In this case, I don't think small multiples are the best approach. Small multiples work well for quickly comparing the global patterns of subsets of data, but make it hard to compare whether individual sections are higher or lower. I have a hard time decoding your plots.
