### ISSUE TITLE
use `.data$` instead of `.$` for Exercise 24.3.3 & Exercise 24.3.4

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#169]
I think that the biggest drawback for dplyr is using system function name as variable name.

For example,

```r
tibble::tribble(
    ~date, ~mean,
    '2018-11-22', 1
)
```
would cause great trouble for `dplyr::mutate()` and so on.

**Comment by dongzhuoer** [comment]
`date` and `wday` are both function name, so I understand that using `.$` can reduce ambiguity.

But there is another problem, `x %>% f(g(.))` means `x %>% f(., g(.))`

From `` ?`%>%` ``
> `iris %>% subset(1:nrow(.) %% 2 == 0)` is equivalent to iris %>% subset(., 1:nrow(.) %% 2 == 0)

**Comment by dongzhuoer** [comment]
So every time I use `.` in nested function, I would add `{}` to create a lambda expression.

**Comment by dongzhuoer** [comment]
what about `.data$` since they are all inside `dplyr::mutate()`

**Comment by dongzhuoer** [comment]
I checked the book, it neither introduces `.$` not `.data$`. 

We may need to add a paragraph explaining why we use `.data$`.

**Comment by jrnold** [comment]
At one point `.$` was required to get `case_when()` to work within `mutate()`. This was before tidyeval standardized everything. I'll need to check what will work now.

**Comment by jrnold** [comment]
Fixed in 159facabaafc697b2
