### ISSUE TITLE
Exercise 24.2.2, add precise equation

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#170]
How do you get the conclusion?

**Comment by dongzhuoer** [comment]
I use an example
Let's assume  `log(price) = 1 + 1.5 * log(carat)`

log(price0) = 1 + 1.5 * log(carat0)
log(price1) = 1 + 1.5 * log(carat1)

if carat1 = 1.01 * carat0 (1% increase)

log(price1) = 1 + 1.5 * log(carat1) = 1 + 1.5 * log(1.01 * carat0) =  1 + 1.5 * log(1.01) + 1.5 * log(carat1) = log(price0) +  1.5 * log(1.01)
log(price1) - log(price0) =  1.5 * log(1.01)
price1 / price0 = e ^ ( 1.5*log(1.01) )

the increase is e ^ ( 1.5*log(1.01) ) - 1 = 0.01503744 =  1.503744%, close to 1.5%

**Comment by jrnold** [comment]
It's a typical approximation made when interpreting linear regressions with logarithms in either the response or predictors: E.g. https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqhow-do-i-interpret-a-regression-model-when-some-variables-are-log-transformed/.

**Comment by dongzhuoer** [comment]
Great. You may add that link to the answer.
