### ISSUE TITLE
Exercise 5.6.7.2 possible typo

### ISSUE THREAD

**Issue by RandallEW** [jrnold/r4ds-exercise-solutions#179]
Not sure if typo or just spelling preference, but the answers to Exercise 5.6.7.2 changed the name of the data frame used throughout R4DS section 5.6 from "not_cancelled" to "not_canceled".

**Comment by RandallEW** [comment]
Disregard - after working further through the solutions, I see it's just a spelling preference.

**Comment by jrnold** [comment]
Yeah, it's a spelling preference (or choice), but I should be consistent with R4DS.
