### ISSUE TITLE
Excercise 10.6.2 typo

### ISSUE THREAD

**Issue by JamesCuster** [jrnold/r4ds-exercise-solutions#181]
There is an unnecessary "you" in the last sentence of your answer. Here is the sentence as is.

"Then you what that code does depends on length(vars) and you’d have to write code to account for those situations or risk bugs."

Should be 
"Then what that code does depends on length(vars) and you’d have to write code to account for those situations or risk bugs."

**Comment by dongzhuoer** [comment]
fixed in bc407b43ab60f36966ece3d8e1b1ab8c4a2f52f1

**Comment by dongzhuoer** [comment]
fixed in bc407b43ab60f36966ece3d8e1b1ab8c4a2f52f1
