### ISSUE TITLE
Exercise 12.6.1, check implicit missing values

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#189]
I think a easy and straightforward way is to use `complete()`

```r
tidyr::who %>% nrow
## [1] 7240

tidyr::who %>% tidyr::complete(country, year) %>% nrow
## [1] 7446
```

We can see that there are 7446 - 7240 = 206 implicit missing values

**Comment by dongzhuoer** [comment]
quick links
- question https://r4ds.had.co.nz/tidy-data.html#case-study
- answer https://jrnold.github.io/r4ds-exercise-solutions/tidy-data.html#exercise-12.6.1

**Comment by jrnold** [comment]
I agree, there should be a discussion of implicit missing values. I rewrote the answer with that included. What do you think?

**Comment by dongzhuoer** [comment]
Great!
