### ISSUE TITLE
dep_time_min and arr_time_min are computed at the start of Ex. 5.5.2 but not referred to subsequently

### ISSUE THREAD

**Issue by kxchia1** [jrnold/r4ds-exercise-solutions#191]
Hi there,

In Exercise 5.5.2, `dep_time_min` and `arr_time_min` are computed at the start to find out the relationship between `dep_time`, `arr_time`, and `air_time`, but they are not referred to in subsequent lines of code, and `air_time_diff` is still computed using the original `dep_time` and `arr_time` columns found in the `flights` data frame.

**Comment by jrnold** [comment]
Thanks for catching that! How does the new solution look? I fixed the code, but I still need to clean up the text of the solution.

**Comment by kxchia1** [comment]
Hi @jrnold, thanks for your reply. It looks good now!

**Comment by jrnold** [comment]
Anything else you think needs improvement in that question?

**Comment by kxchia1** [comment]
No, I think the solution makes sense to me now. Thanks! (should I close this issue myself ? Sorry this is the first issue I open on GH)

**Comment by jrnold** [comment]
I'll close it. While I'm looking at it, I'll want to take another read-through to edit it.
