### ISSUE TITLE
Wrong Answer in 7.5.1.2

### ISSUE THREAD

**Issue by eric-k-zhu** [jrnold/r4ds-exercise-solutions#199]
You say that 
"The is a weak positive relationship between color and price"

It should be "There" and the relationship is weak negative between color and price. The color of the diamond goes from J(worst) to D(best). Consult dataset documentation with "?diamonds" to double check

**Comment by jrnold** [comment]
Nice catch. You are correct that D is the best and J is the worst. 

The levels of the `ggplot2::diamonds$color` are specified correctly in the documentation, but incorrectly in the variable. See tidyverse/ggplot2/pull/3146.
