### ISSUE TITLE
Fix issue in Ex 13.5.2

### ISSUE THREAD

**Issue by jrnold** [jrnold/r4ds-exercise-solutions#220]
https://hyp.is/bdoIPEItEemWc8NcFn1CHg/jrnold.github.io/r4ds-exercise-solutions/relational-data.html

**Comment by r2ressler** [comment]
The posted solution does not filter out for flights without a tailnum. That leads to NA as a "tailnum" so increases the final solution by 2,512 flights to 230, 902. Filter out the missing tailnums
```
planes_gte100 <-
  filter(flights) %>% filter(!is.na(tailnum)) %>% 
  group_by(tailnum) %>% ... 
 ```
to get 228, 390. 

Just a thought.  I really enjoy the book and the way you expand upon the minimal solutions.
