### ISSUE TITLE
Forgot to remove nans in Ex 5.7.6

### ISSUE THREAD

**Issue by bhishanpdl** [jrnold/r4ds-exercise-solutions#248]
This is a wonderful solution/tutorial to learn data science using R. I have learned a lot using this tutorial. However, I found one possible typo/omission in the solution to Exercise 5.7.6 Second part:

Actual code:
```R
air_time_delayed <-
  flights %>%
  group_by(origin, dest) %>%
  mutate(
    air_time_min = min(air_time),
    air_time_delay = air_time - air_time_min,
    air_time_delay_pct = air_time_delay / air_time_min * 100
  )
```

IMO it should have been:

```R
air_time_delayed <-
  flights %>%
  group_by(origin, dest) %>%
  mutate(
    air_time_min = min(air_time,na.rm=TRUE),
    air_time_delay = air_time - air_time_min,
    air_time_delay_pct = air_time_delay / air_time_min * 100
  )
```

Then it also changes the result you presented:

> The most delayed flight in air in minutes was HA51 from JFK to HNL which departed on 2013-02-06 at 08:53. It took 111 minutes longer than the flight with the shortest air time on its route.

It becomes:

> The most delayed flight in air in minutes was DL841 from JFK to SFO which departed on 2013-07-28 at 17:27. It took 189 minutes (3 hours 9 minutes) longer than the flight with the shortest air time on its route.

**Comment by jrnold** [comment]
Thanks!
