### ISSUE TITLE
All Chapters Shifted Around

### ISSUE THREAD

**Issue by bob100000000000** [jrnold/r4ds-exercise-solutions#256]
I was working through chapter 3 of the R for Data Science book/solutions manual and it seems as though some chapter titles were moved around and numbers were changed

For example the chapter 3 has sections both in 3 and 16 https://jrnold.github.io/r4ds-exercise-solutions/dates-and-times.html , meanwhile each section doesn't match up, with the book itself. https://r4ds.had.co.nz/data-visualisation.html

It seems to have changed in the middle of me looking at it, and I don't think I did anything to shift it myself, but it may have been something I did on my end.

**Comment by jrnold** [comment]
I'm not sure what happened. Nothing should have changed the order of the chapters, but now they are being put in alphabetical order for some reason. I'm reverting back to an older version to see if that fixes it until I figure out what happened.

**Comment by jrnold** [comment]
Thanks for catching this.

Fixed with commit 62a91fffd3fd5140d0f2fd18aacd590f89498541.
