### ISSUE TITLE
3.9.3 typo in answer

### ISSUE THREAD

**Issue by JamesCuster** [jrnold/r4ds-exercise-solutions#26]
The answer provided is:
coord_map() uses map projection to project 3-dimensional Earth onto a 2-dimensional plane. By default, coord_map() uses the Mercator projection. However, this projection must be applied to all geoms in the plot. coord_quickmap() uses a faster, but approximate map projection. This approximation ignores the curvature of Earth and adjusts the map for the latitude/longitude ratio. This transformation is quicker than the because the shapes do not need to be transformed.

There is a type in the last sentence. It should read something more like: "This transformation is quicker than coord_map() because the shapes do not need to be transformed."

**Comment by jrnold** [comment]
Thanks!
