### ISSUE TITLE
3.9.4 answer typo

### ISSUE THREAD

**Issue by JamesCuster** [jrnold/r4ds-exercise-solutions#27]
the text reads as:
"If we didn’t include geom_point, then the line is no longer at 45 degrees:

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() +
  geom_abline()"

geom_point() was not excluded, coord_fixed() was.

**Comment by jrnold** [comment]
Thanks!

**Comment by JamesCuster** [comment]
You're welcome. I'll let you know if I find anything else as I work through the book.
