### ISSUE TITLE
Minor issue with 5.3.1 exercise 3 sln

### ISSUE THREAD

**Issue by jhoeting** [jrnold/r4ds-exercise-solutions#288]
First, thanks for the solutions.  They are helpful.  

Please briefly describe your problem and what output you expect.

-   Include a link to page, and reference the exercise number (if applicable).

https://jrnold.github.io/r4ds-exercise-solutions/transform.html#arrange-rows-with-arrange

Answer to Section 5.3.1:  Sort flights to find the fastest flights.

Two issues:
1.  Fastest implies speed so I think the answer has to be based on speed, not flight duration.  If the question wanted duration it should say shortest. 

2.  Not really a typo, but the so the 60 is superfluous in "distance / air_time * 60" .  Since you aren't examining these data just sorting based on this criterion you don't need the 60.   

-   If code is producing an error, include both the code and the error message, as well as the
    output of `sessionInfo()`.

suggested new code:  
arrange(flights, distance / air_time )

**Comment by jrnold** [comment]
Good points. I'll rewrite the solution.
