### ISSUE TITLE
14.3.5.2 - select substring or entire word?

### ISSUE THREAD

**Issue by r2ressler** [jrnold/r4ds-exercise-solutions#327]
This about how to interpret the phrase "match words" in the question. The code matches the substring that begins with the first pair of letters and ends with the second pair. It does match  select the entire word.
Adding .* to the beginning outside the group and the end will match the entire word.

".*([A-Za-z][A-Za-z]).*\\1.*"

**Comment by r2ressler** [comment]
note sure why my first * disappeared in my paste; it should start ".*([A

**Comment by r2ressler** [comment]
my error - you are using str_sub and not str_view

**Comment by jrnold** [comment]
Is there
