### ISSUE TITLE
Exercise 14.4.2.2

### ISSUE THREAD

**Issue by r2ressler** [jrnold/r4ds-exercise-solutions#328]
The definition of a "word" and solution are consistent. 

However, the solution selects "It" instead of the actual "It's" in the third sentence. Adding an apostrophe to the regexp will add contractions to the extractions

"^[A-Za-z']+"

**Comment by jrnold** [comment]
👍  I think that's a good improvement. In general, there are still some edge case; for example, it would match a single `'` or `'''`.  But this seems to cover the `sentences` corpus.
