### ISSUE TITLE
Typo in Exercise 13.5.2

### ISSUE THREAD

**Issue by neander09** [jrnold/r4ds-exercise-solutions#346]
https://jrnold.github.io/r4ds-exercise-solutions/relational-data.html#exercise-13.5.2

> Now, I will semi join the data frame of lights that have flown at least 100 flights to the data frame of flights to select the flights by those planes.

I think you meant "... join the data frame of _planes_ that have flown ..."

**Comment by jrnold** [comment]
Thanks. Fixed.
