### ISSUE TITLE
Update 12.3 with pivot_longer & pivot_wider

### ISSUE THREAD

**Issue by jlbeaudry** [jrnold/r4ds-exercise-solutions#355]
R4DS (Chapter 12.3) has replaced spread & gather with 'pivot_longer' and 'pivot_wider' (https://r4ds.had.co.nz/tidy-data.html#wider).  

It'd be great if you could update your chapter and solutions to reflect this change. Thanks!

**Comment by jjacob12** [comment]
Just backing up on this issue - yes it would be great if you could update spreead and gather.
Thanks.

**Comment by Shurakai** [comment]
This is not just search and replace, the text of the exercises changed a bit as well. The exercises themselves seem to be mostly the same though.

**Comment by jjacob12** [comment]
Dear Christian,

Many thanks for the update - much appreciated!

Kind Regards,
Dr S J Jacob
j.jacob1@btinternet.com

**Comment by jrnold** [comment]
Thanks bringing this to my attention, and sorry for the delay. I've updated the chapter. Do you have any thoughts on the solutions?

**Comment by jlbeaudry** [comment]
> Thanks bringing this to my attention, and sorry for the delay. I've updated the chapter. Do you have any thoughts on the solutions?

Hi there,
Thanks for updating it. I've worked through 3 of the 4 exercises, if you'd like my solutions to them? I apparently got distracted and didn't finish the last one... Please let me know how'd you like to me to send them.

**Comment by jjacob12** [comment]
Hello,
Thanks for helping out with this. If possible could  you please send your solutions as an R Markdown file published on GitHub?

Best wishes,
John

Dr S J Jacob
j.jacob1@btinternet.com
