### ISSUE TITLE
Exercise 14.3.4.1.1

### ISSUE THREAD

**Issue by mroviras** [jrnold/r4ds-exercise-solutions#359]
Hey,

Thank you so much for your work!

A very small issue. At exercise 14.3.4.1.1 (https://jrnold.github.io/r4ds-exercise-solutions/strings.html#repetition), you suggest _"str_view_all(x, "C[LX]{0,1}")"_ as an alternative to _"str_view_all(x, "C[LX]+")"_. However, the results in my computer do not look exactly the same.

Following the solutions you provide above in the same exercise, I think the answer could be: str_view_all(x, "C[LX]{1,}"). This works in my computer.

I am not sure if this is really a mistake or it was intentional. Just in case.

Best wishes, and again, thanks for your work!

Marti

**Comment by jrnold** [comment]
Thanks. It was a mistake and not intentional. Updating the answer with your fix.
