### ISSUE TITLE
Possible mistake in Exercise 3.7.2 

### ISSUE THREAD

**Issue by TheMksConnection** [jrnold/r4ds-exercise-solutions#360]
In the answer, you say "The default stat of geom_bar() is stat_bin()."

It seems to me that the default stat of geom_bar() is stat_count(). However, I am a total beginner.

**Comment by Shurakai** [comment]
Yes, you're quite right. There's a PR already, #356

**Comment by jrnold** [comment]
Thanks for catching this.  As noted #356 fixes this.
