### ISSUE TITLE
7.5.1.3: ggplot2 3.3.0 now deprecated ggstance

### ISSUE THREAD

**Issue by Shurakai** [jrnold/r4ds-exercise-solutions#368]
ggplot2 can now create horizontal boxplots out of the box, so this might be useful to be mentioned in the solution for Exercise 7.5.1.3

**Comment by jrnold** [comment]
Good point. I'm adding examples and a note about this to the answer.

**Comment by Shurakai** [comment]
Thanks! Small hint: There was a little spelling error in that commit, "switchingn".
