### ISSUE TITLE
15.3.1 Show how to reorder factors

### ISSUE THREAD

**Issue by Shurakai** [jrnold/r4ds-exercise-solutions#371]
An interesting side-effect of using `coord_flip()` is that the labels are now presented from lowest (top) to highest (bottom). When presented on the x-axis, they go from highest to lowest on the x-axis, which is counter-intuitive. It would be nice to add an example on how to achieve this. Maybe `fct_reorder` will work?

**Comment by jrnold** [comment]
This is a fair point, but since R4DS doesn't introduce `fct_reorder` until a later section, I don't want to use it in the solution.

**Comment by jrnold** [comment]
But I made a note of your comment and that `fact_reorder()` would be introduced in the next section.
