### ISSUE TITLE
5.6.6 not consistent with the book

### ISSUE THREAD

**Issue by xinrui112** [jrnold/r4ds-exercise-solutions#372]
- book: 5.6.6: "count # of flights before first delay of greater than 1h."
5.6.7: "sort argument to count()."

- website page: the answer to 5.6.6 is actually to 5.6.7.
The answer to 5.6.6 is missing.

**Comment by jrnold** [comment]
Are you referring to the printed text or the online version of R4DS? I think the questions and answers match those currently on the online version: https://r4ds.had.co.nz/transform.html#exercises-12.
