### ISSUE TITLE
Typo in Exercise 3.2.5

### ISSUE THREAD

**Issue by vzei** [jrnold/r4ds-exercise-solutions#374]
There is an additional letter in the code. The code runs neverthless but it still is confusing.
Exercise 3.2.5

mpg %>%
  count(class, drv) %>%
  complete(class, drv, fill = list(n = 0L)) %>%
  ggplot(aes(x = class, y = drv)) +
  geom_tile(mapping = aes(fill = n))

-> "n=0L", the "L" is probably not necessary

**Comment by jrnold** [comment]
You're right; it's confusing.  `0L` creates an integer value of 0, while `0` creates a numeric (floating point) value of 0 (see Chapter 20). R is pretty forgiving with data types so this will work without the `L`. It looks like R4DS doesn't introduce or use it, so I'll remove it here to get rid of any confusion.
