### ISSUE TITLE
Exercise 14.4.5.1 Question Answers

### ISSUE THREAD

**Issue by clemonsa** [jrnold/r4ds-exercise-solutions#376]
Please briefly describe your problem and what output you expect.

-  http://nickg.bio/_posts/ngiangre/r_for_data_science_solutions.html#exercise_14451
   Exercise 1: Replace all forward slashes in a string with backslashes.

  The wrong solution is provided, instead it is the solution for exercise 1 in 14.4.6.1.

Below my solution:

```
# Replace all forward slashes with backslashes
slash <- "http:\\\\rstudio.com\\"
str_replace_all(slash, "\\\\", "/")
# [1] "http://rstudio.com/"
```
Exercise 2: Implement a simple version of str_to_lower() using replace_all()

No solution is provided. Below is my solution:

```
#implement simpler version of str_to_lower() using str_replace_all()

str_replace_all(LETTERS, "[[:alpha:]]", letters)

# [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s" "t" "u" "v" "w" "x" "y" "z"
```
Exercise 3: Switch the first and last letters in words. Which of those strings are still words?

No solution is provided, someone couldn't figure it out. Below is my solution:

```
#switch the first and last letters in "words"; which of these are still words?

str_replace(words, "^([[:alpha:]])([[:alpha:]]*)([[:alpha:]])$", "\\3\\2\\1") %>% head()
# [1] "a"        "ebla"     "tboua"    "ebsoluta" "tccepa"   "tccouna"
```

**Comment by jrnold** [comment]
I think you have this confused with a different repo. This repo has the source for https://jrnold.github.io/r4ds-exercise-solutions/.  

- This repo has an answer for 14.4.6.1.
- Exercise 2: I don't think this works. Try it on an input other than `LETTERS`. 
- Exercise 3: These solutions have an answer , but I'm adding an alternative using the POSIX character class.  Thanks!
