### ISSUE TITLE
add an additional explanation for Exercise 11.2.4

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#53]
Your answer is pretty good. But you might add that `read_csv()` also has a `quote` parameter

```r
read_csv("x,y\n1,'a,b'", quote = "'")
```

```
# A tibble: 1 x 2
      x y    
  <int> <chr>
1     1 a,b  
```

**Comment by jrnold** [comment]
That might have been added after R4DS was written.

**Comment by jrnold** [comment]
I opened this issue https://github.com/hadley/r4ds/issues/696
