### ISSUE TITLE
Exercise solutions - Data Transformation - 5.2.4

### ISSUE THREAD

**Issue by ricardosasso** [jrnold/r4ds-exercise-solutions#564]
_The value of NA & FALSE is FALSE because anything and FALSE is always FALSE. If the missing value were TRUE, then TRUE & FALSE == **TRUE**, and if the missing value was FALSE, then FALSE & FALSE == **TRUE**._

In my opinion this is not correct. TRUE & FALSE == **FALSE**, and FALSE & FALSE == **FALSE**

Also,

_For NA | FALSE, the value is unknown since TRUE | FALSE == TRUE, but FALSE | FALSE == **TRUE**_

Actually, FALSE | FALSE == **FALSE**

**Comment by jrnold** [comment]
It's not just your opinion, the current answer is incorrect. Those are all typos due to sloppy copy and pasting.
