### ISSUE TITLE
Better way to supply packages needed in the answer

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#61]
It's a good practice to explicit `library()` the packages needed in the beginning of a chapter. But sometimes that might be too far away, for example, we need **lubridate** for Exercise 19.4.2

**Comment by dongzhuoer** [comment]
The is another problem particularly for Exercise 19.4.2. 

```r
greet <- function(time = lubridate::now()) {
  hr <- hour(time)
  # I don't know what to do about times after midnight,
  # are they evening or morning?
  if (hr < 12) {
    print("good morning")
  } else if (hr < 17) {
    print("good afternoon")
  } else {
    print("good evening")
  }
}
```

Although it works, `hour()` also comes from lubridate, which is inconsistent and causes confusion.

By the way, we can use `Sys.time()` instead of `lubridate::now()`. However, the question requires the latter.

**Comment by jrnold** [comment]
What is the suggestion? I think the current approach is correct and the same followed by R4DS. Load most packages at the start, and reference some functions or objects with `::` if the package is only used once, or to avoid ambiguity. However, there may be some cases in the code that need to be fixed, such as the one you mentioned. But those cases are bugs/improvements, not a new approach.

**Comment by jrnold** [comment]
I've fixed the one you mentioned. If you notice any other cases, open up a PR or Issue to fix them.

**Comment by dongzhuoer** [comment]
Maybe you can add an explanation in [welcome](https://jrnold.github.io/r4ds-exercise-solutions/index.html) or the first [chapter](https://jrnold.github.io/r4ds-exercise-solutions/introduction.html).

**Comment by jrnold** [comment]
What are you envisioning?
