### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jrnold** [jrnold/r4ds-exercise-solutions#68]
Add Dockerfile to help reproducibly build the book.

**Comment by jdbohrman** [comment]
I'd love to help out with this! Also, @dongzhuoer I'm curious of hearing this method of combining a dockerfile via Travis CI.

**Comment by dongzhuoer** [comment]
You can build docker image (and push it to DockerHub) using Travis, like https://github.com/dongzhuoer/docker-rlang. 
You can also run a docker container and do some staff using Travis, https://github.com/dongzhuoer/build-r4ds/.

**Comment by dongzhuoer** [comment]
Travis won't cache it. You have to pull the image every time. But don't worry, I have proved that it's much faster than the using the R language of Travis (community maintained).
