### ISSUE TITLE
print source code of `rlang::set_names_impl()` for Exercise 20.4.3

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#71]
User can't learn that

> `set_names` adds a few sanity checks: `x` has to be a vector, and the lengths of the object and the names have to be the same.

from merely

```r
purrr::set_names
#> function (x, nm = x, ...) 
#> {
#>     set_names_impl(x, x, nm, ...)
#> }
#> <bytecode: 0x7fc3439f4bf0>
#> <environment: namespace:rlang>
```

**Comment by dongzhuoer** [comment]
https://jrnold.github.io/r4ds-exercise-solutions/vectors.html#exercise-20.4.3

**Comment by jrnold** [comment]
You're right. At one time that must have been true, but it looks like `set_names` changed.
