### ISSUE TITLE
where is the graph for Exercise 20.5.1

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#78]
https://jrnold.github.io/r4ds-exercise-solutions/vectors.html#recursive-vectors-lists#exercise-20.5.1

**Comment by dongzhuoer** [comment]
The code works fine on my own computer.

**Comment by jrnold** [comment]
It looks like something is going wrong with the diagrammeR htmlwidget. I'll have to investigate.
