### ISSUE TITLE
improve answer for 20.3.3

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#95]
If you want to show 

> However, you can represent that value (_exactly_) with a numeric vector at the cost of about two times the memory.

you should show 

```r
> as.numeric(.Machine$integer.max) + 1
[1] 2147483648
```

rather than

```r
as.numeric(.Machine$integer.max) + 1
#> [1] 2.15e+09
```

**Comment by dongzhuoer** [comment]
By the way, I suspect that 2e-308 should mean 2*10^-308^ instead of 2^-308^

**Comment by jrnold** [comment]
Since 1 is real it should coerce the value to numeric and as.numeric isn't needed. That's why you need to add by 1L to keep it an integer

**Comment by dongzhuoer** [comment]
Our intention should be spoke out by the code, not implied by (obscured) syntax rules.

**Comment by jrnold** [comment]
Very good point. The distinction between `1L` and `1` is still obscure, though appearing in more tidyverse stuff due the stricter error checking in R objects. And relying on people remembering coercion rules is impossible since I still figure it out by trial and error many times.
