### ISSUE TITLE
Exercise 3.8.2. What parameters to geom_jitter() control the amount of jittering?

### ISSUE THREAD

**Issue by carajoos** [jrnold/r4ds-exercise-solutions#96]
This exercise asks about geom_jitter but your solutions use geom_point. While this is a way to achieve the same plots it is not the answer to the question and causes confusion as there is no clear way to see how you got from geom_jitter -> position_jitter. I propose the following edited code as more clear examples for this exercise. 

Exercise 3.8.2. {.unnumbered .exercise}
What parameters to `geom_jitter()` control the amount of jittering?
From the position_jitter documentation, there are two arguments to jitter: width and height, which control the amount of vertical and horizontal jitter.

No horizontal jitter

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_jitter(width = 0)
Way too much vertical jitter

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_jitter(width = 0, height = 15)
Only horizontal jitter:

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom(height = 0)
Way too much horizontal jitter:

ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_jitter(height = 0, width = 20)

**Comment by jrnold** [comment]
Looks good to me. Sorry about the confusion. It's old habits, since I was using ggplot2 since before `geom_jitter()` existed. I can add this, or do want to open a pull request?

**Comment by carajoos** [comment]
Thanks!

**Comment by jrnold** [comment]
Thank you. And please let me know if you have any more corections/suggestions. I know that there is much more that can be improved in them!

**Comment by carajoos** [comment]
I can take notes as I find road blocks if you are interested. Like right now I am on exercise in arrange and the solutions use concepts not introduced until later chapters, like select and pipes. I have some familiarity with pipes so I recognize that is what you are using but others may not. So if you are interested in things like that I could just keep running notes and pass them on directly instead of going through stack exchange.

**Comment by jrnold** [comment]
> Like right now I am on exercise in arrange and the solutions use concepts not introduced until later chapters, like select and pipes

This would be really useful! Keeping track of what I know and what was introduced is something that I still find difficult. I wrote these solutions without the intent of them being distributed as widely as they are now, which meant I paid even less attention to that than I should have. 

github issues like this are best. Don't worry about opening up too many of them, as long as they are clear (what you did with this one was more than sufficient).
