### ISSUE TITLE
Exercises use concepts not yet introduced in the book

### ISSUE THREAD

**Issue by carajoos** [jrnold/r4ds-exercise-solutions#97]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

Multiple exercises use concepts, such as pipes, that are yet to be covered in the book. Here is a list of solutions with this issue.

Also, one of the below code examples does not produce the correct (at least as I think it should be, I could be wrong) answer due to mathematical error

1.

5.5.3 {unnumbered exercise} - uses pipes which isn't introduced until 5.6

arrange(flights, air_time) %>%
  select(origin, dest, air_time) %>%
  head()

Suggested replacement code-

new <- arrange(flights, air_time)
select(new, origin, dest, air_time)
head(new)

2. 
Exercise 5.4.1 {.unnumbered .exercise} - uses regular expressions which isn't introduced until 5.6, I only know this because I asked a friend who is much more experienced than I in R. I do not know how to fix this code since I have just started chapter 9! I wil

3.
Exercise 5.5.1 - Uses pipes and code does not compute the correct values and I find the use of %% confusing and seems to add more code. 

mutate(flights, dep_time_mins = dep_time%/%100 * 60 + dep_time%%100, 
    sched_dep_time_mins = sched_dep_time%/%100 * 60 + sched_dep_time%%100) %>% 
    select(dep_time, dep_time_mins, sched_dep_time, sched_dep_time_mins)
This is the resulting tibble
# A tibble: 336,776 x 4
   dep_time dep_time_mins sched_dep_time sched_dep_time_mins
      <int>         <dbl>          <int>               <dbl>
 1      517           317            515                 315
 2      533           333            529                 329
 3      542           342            540                 340

dep_time_mins should be 310 not 317   
 (517/100)*60
[1] 310.2
and sched_dep_time_mins should be 309 not 315
 (515/100)*60
[1] 309

I suggest this code which does not use pipes and skips the %% notation.

new2<- mutate(flights, 
       dep_time_mins = (dep_time / 100)*60,
       sched_dep_time_mins = (sched_dep_time / 100)*60) 
select(new2, dep_time, dep_time_mins, sched_dep_time, sched_dep_time_mins)

Which results in this tibble with the correct values

# A tibble: 336,776 x 4
   dep_time dep_time_mins sched_dep_time sched_dep_time_mins
      <int>         <dbl>          <int>               <dbl>
 1      517          310.            515                309 
 2      533          320.            529                317.

Here is the code in the portion which creates a function first
time2mins <- function(x) {
  (x / 100) * 60
}

new3 <- mutate(flights, 
       dep_time_mins = time2mins(dep_time),
       sched_dep_time_mins = time2mins(sched_dep_time))

select(new3,dep_time, dep_time_mins, sched_dep_time, sched_dep_time_mins)

4.

Exercises 5.5.2 & 5.5.3 - solution doesn't seem to work and uses pipes

 I do not understand how this code results in something that shows the problem is due to a time zone or next day departure. Maybe the solutions are switched around because I see the 1440 is a 25 hour period so that would account for departing the next day? To me if it was due to a time zone difference the differences between air time and `arr_time - dep_time' would always be in 60 min increments, which the results are not. More clarification is needed, at least for me!

The comment in 5.5.2 "As with the previous question, we will need to Since arr_time and dep_time may be in different time zones,"  suggests these 2 solutions are inverted. I can't quite reconcile this in my mind how to fix it as I am muddled going back and forth!

5.

Exercise 5.5.6 uses Tibble in solution which has not been introduced. I learn from this but would not have used it on my own.

**Comment by jrnold** [comment]
Thanks! I'm going through this now.

5

> .5.3 {unnumbered exercise} - uses pipes which isn't introduced until 5.6
> 
> arrange(flights, air_time) %>%
> select(origin, dest, air_time) %>%
> head()
> 
> Suggested replacement code-
> 
> new <- arrange(flights, air_time)
> select(new, origin, dest, air_time)
> head(new)

I'm going to get rid of `head()` and `select()` since they haven't been introduced and the examples in the book don't use them. I wanted to show the relevant columns, but the user will have to interact to get them.

**Comment by jrnold** [comment]
> Exercise 5.4.1 {.unnumbered .exercise} - uses regular expressions which isn't introduced until 5.6, I only know this because I asked a friend who is much more experienced than I in R. I do not know how to fix this code since I have just started chapter 9! 

Thanks. I decided to keep it, while adding a not that these are covered later in Chapter 9. I also expanded the discussion of the examples.

**Comment by jrnold** [comment]
> Exercise 5.5.1 - Uses pipes and code does not compute the correct values and I find the use of %% confusing and seems to add more code.

> mutate(flights, dep_time_mins = dep_time%/%100 * 60 + dep_time%%100,
> sched_dep_time_mins = sched_dep_time%/%100 * 60 + sched_dep_time%%100) %>%
> select(dep_time, dep_time_mins, sched_dep_time, sched_dep_time_mins)

The code here is correct (well, almost correct. I forgot to handle the special case of midnight).
Take `517`. This corresponds to `05:17`. The minutes since midnight is `5 * 60 + 17`. 

```
> 517 %/% 100
[1] 5
> 517 %/% 100
[1] 5
> 517 %/% 100
[1] 5
> 517 %/% 100
[1] 5
> 517 %% 100
[1] 17
> 5 * 60 + 17
[1] 317
> 517 %/% 100 * 60 + 517 %% 100 
[1] 317
```
However,  dividing by 100 doesn't work, because it is like `5 * 60 + 0.17 *60`.  However, the 17 minutes after the hour are already in minutes and don't need to by multiplied by 60. 
```
> 517 / 100
[1] 5.17
> 5 * 60 + 0.17 * 60
[1] 310.2
```

The `%%` is called the modulo operator and gives the remainder. Which is why I use it to get the minutes part. In this format, the minutes are the remainder after dividing by 100.

**Comment by jrnold** [comment]
Would adding the previous discussion to the answer help clarify it?

**Comment by carajoos** [comment]
Ahhhh of course! That remainder notation really twists my mind around. Sorry about that!

**Comment by carajoos** [comment]
Hi again,

 

Ahhh I see that I missed those operators in the book, it was between 2 things I was familiar with and I just zoomed by. I am guessing I got to that point somewhere around 3 PM!  Sorry about that! Now the modular arithmetic makes more sense and I see what I should have done with the given information. 

 

Except now I just have no idea how the final products tell us that we missed time zones and next day departures. So this “Story problem” has me just generally flummoxed I guess………. Ok, for 5.5.1,  after playing with it a bit I suggest the below without pipes, just add in a new field that subtracts the 2 new columns created to drive how it works now. It isn’t more correct just helped my fuzzy brain see the solution more easily.

 

mutate(flights,

       dep_time_mins = time2mins(dep_time),

       sched_dep_time_mins = time2mins(sched_dep_time), 

       dep_dif = dep_time_mins - sched_dep_time_mins)

  select(flights, dep_time, dep_time_mins, sched_dep_time, sched_dep_time_mins, dep_dif)

 

For 5.5.2 I see that air_time_diff is between 343 and 345. I just don’t see how that tells us anything because a > 5 hour air time difference seems very unlikely……. Aaaaa, so this was confusing to me because an over 5 hour difference air time didn’t make sense to me. It seems impossibly high. I re-arranged ascending and the solution was more obviously correct with this display since a difference in airtime of a few minutes is more palatable. I’m still a little flummoxed on how a flight could take 5.7 hours less time than expected! Here is my code without pipes. 

 

air_times <- mutate(flights,

       arr_time_min = time2mins(arr_time),

       dep_time_min = time2mins(dep_time),

       air_time_2 = (arr_time_min - dep_time_min + 1440) %% 1440,

       air_time_diff = air_time_2 - air_time,

       airtime_delay_hours = air_time_diff/60)

 

 

  arrange(air_times,(abs(air_time_diff)))

  select(air_times,air_time, air_time_diff, airtime_delay_hours)

 

 

 

I’m sorry to take up your time with my oversight. I did learn a lot from this however. I have been struggling with the switch from SAS to R and my friend suggested this book and it has been extremely helpful. The tidyverse approach fits much more with the approach and flow I learned in SAS and since I learn stats and SAS together the 2 are very muddled together. I am very excited to feel like my years of lost wrestling matches with R may be over and we can start to be more at peace!

 

I VERY much appreciate your solutions because without them I would not have learned so much so quickly going through this.

 

Best

Cara

**Comment by jrnold** [comment]
Please keep asking questions! I appreciate them. Even if it's something you "missed" that means it wasn't clear in the solution. My solutions were originally much more sparse and I've mostly been adding to them as people raise issues. So keep asking.

**Comment by jrnold** [comment]
I need to expand out the discussion of these questions.  Honestly, for this question, I think I wrote a little and then didn't want to deal with all the annoying data cleaning things, probably because it was late in the day and I was tired. So I need to expand it a bit.

> I just don’t see how that tells us anything because a > 5 hour air time difference seems very unlikely……. Aaaaa, so this was confusing to me because an over 5 hour difference air time didn’t make sense to me. It seems impossibly high. I re-arranged ascending and the solution was more obviously correct with this display since a difference in airtime of a few minutes is more palatable. 

You have the right intuition. Check the origin and destination of the flight. 

I think there are three issues with the data:

1. Flight lands the next day. The difference should be 1440 minutes (24 hours)
2. Flight crosses time zones. The difference should be factors of 60 - and could be checked by looking at the time zones of the airports (in the `airports` data frame).
3. Anything else could be due to time spent on the runway. The data is missing some columns. From what I can tell, air time is determined from when the aircraft takes off and lands, while the arrival and departure times are when the aircraft leaves or arrives at the gate.

It's not implausible that the answer to this question was more annoying than the author originally intended.

**Comment by carajoos** [comment]
Thanks! That all makes sense. 

 

I am on exercise 12.3.3 and I can’t figure out how to add in a column that gives the observation number. I have tried add_tally() and add_count() and they don’t give the observation number. Can you include the code to create that new column? I can’t seem to find any way to add the obs # by name. Just the total # for each name. Is it explained somewhere up above that I missed? I tried googling this but the term observation is just too common to find anything useful!

**Comment by carajoos** [comment]
##12.3.4  I suggest this code instead as it is consistent with the method in the text and achieves the same table functionally. Although why we would ever want a table that says if a man is pregnant or not I am not sure :)

  preg <- tribble(
  ~pregnant, ~male, ~female,
  "yes",     NA,    10,
  "no",      20,    12
)%>%
  
  gather(`male`,`female`,key = "sex", value = "count")

# A tibble: 4 x 3
  pregnant sex    count
  <chr>    <chr>  <dbl>
1 yes      male      NA
2 no       male      20
3 yes      female    10
4 no       female    12

**Comment by jrnold** [comment]
> Although why we would ever want a table that says if a man is pregnant or not I am not sure :)

I don't think it said that it was human. It could be seahorse data. :-)

Thanks! I used that code. Also, I expanded the answer a lot. Although it was earlier, I think that the question (and your response) was touching on the points raised in the Missing Values section (12.5). See if my answer made sense.

**Comment by jrnold** [comment]
Found anything else? I'm going to close this to clear my mind. If you find something else, open a new issue. Thanks!

**Comment by carajoos** [comment]
I'm sorry I've been working on another project the last few days. I'll get back to it tomorrow.

**Comment by jrnold** [comment]
No problem. I appreciate anything you contribute and happy to answer any questions you have. I was giving you a heads up about why I was closing this issue.
